export class FusionError extends Error {
  constructor(
    readonly code: string,
    message: string,
  ) {
    super(message)
    this.name = 'FusionError'
  }
}

export const FUSION_CONTEXT_BUDGET = 'FUSION_CONTEXT_BUDGET'
export const REVISION_CONFLICT = 'REVISION_CONFLICT'
export const REVISION_STALE = 'REVISION_STALE'
export const EVENT_CONFLICT = 'EVENT_CONFLICT'
export const FLUSH_FAILED = 'FLUSH_FAILED'
export const CHECKSUM_MISMATCH = 'CHECKSUM_MISMATCH'
export const LEASE_BUSY = 'LEASE_BUSY'
export const LEASE_GENERATION = 'LEASE_GENERATION'
export const PROFILE_UNAVAILABLE = 'PROFILE_UNAVAILABLE'
export const SPEND_UNAUTHORIZED = 'SPEND_UNAUTHORIZED'
export const APPROVAL_SCOPE = 'APPROVAL_SCOPE'
export const OUTCOME_UNKNOWN = 'OUTCOME_UNKNOWN'
export const NEEDS_REPAIR = 'NEEDS_REPAIR'
export const USAGE_MERGE_CONFLICT = 'USAGE_MERGE_CONFLICT'
export const USAGE_LEDGER_REQUIRED = 'USAGE_LEDGER_REQUIRED'
export const CONTROL_BLOCKED = 'CONTROL_BLOCKED'
export const REVIEW_RESULT_CONFLICT = 'REVIEW_RESULT_CONFLICT'
export const REVIEW_TICKET_REQUIRED = 'REVIEW_TICKET_REQUIRED'
export const WORK_ORDER_CONFLICT = 'WORK_ORDER_CONFLICT'
export const STORE_MIGRATION_REQUIRED = 'STORE_MIGRATION_REQUIRED'
